[workspace]
members = [".", "serde-teamspeak-querystring"]

[package]
name = "teamspeak-autochannel"
version = "0.3.2"
edition = "2021"

[dependencies]
anyhow = "1"
clap = "3.1"
env_logger = "0.9"
log = "0.4"
redis = "0.21"
serde = "1.0"
serde-teamspeak-querystring = { path = "serde-teamspeak-querystring" }
serde_derive = "1.0"
telnet = "0.2.1"
