[workspace]
members = [".", "serde-teamspeak-querystring"]

[package]
name = "teamspeak-autochannel"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = "3.1"
env_logger = "0.9"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde-teamspeak-querystring = { path = "serde-teamspeak-querystring" }
telnet = "0.2.1"
