name: Build Releases

on:
  push: 
  workflow_dispatch:
    branches:
      - master


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        job:
          - { os: macos-latest }
          - { os: ubuntu-latest }
          - { os: windows-latest }

    name: Build
    runs-on: ${{ matrix.job.os }}
    env:
      RUST_BACKTRACE: full

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          default: true
          override: true

      - name: Environment
        run: |
          git submodule update --init --recursive

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile release

      - name: Rename binary
        id: rename
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            BIN='teamspeak-autochannel_linux_amd64'
            mv target/release/teamspeak-autochannel target/release/$BIN
          elif [ "$RUNNER_OS" == "macOS" ]; then
            BIN='teamspeak-autochannel_darwin_amd64'
            mv target/release/teamspeak-autochannel target/release/$BIN
          else
            BIN='teamspeak-autochannel_windows_amd64.exe'
            mv target/release/teamspeak-autochannel.exe target/release/$BIN
          fi
          echo "::set-output name=bin::target/release/$BIN"
      - uses: actions/upload-artifact@v2
        with:
          name: teamspeak-autochannel_linux_amd64
          path: target/release/teamspeak-autochannel_linux_amd64
      - uses: actions/upload-artifact@v2
        with:
          name: teamspeak-autochannel_darwin_amd64
          path: target/release/teamspeak-autochannel_darwin_amd64
      - uses: actions/upload-artifact@v2
        with:
          name: teamspeak-autochannel_windows_amd64.exe
          path: target/release/teamspeak-autochannel_windows_amd64.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.rename.outputs.bin }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_aarch64:
    name: Cross build
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          profile: minimal
          default: true
          override: true
      - name: Environment
        run: |
          git submodule update --init --recursive
      - name: Build aarch 64 binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target aarch64-unknown-linux-musl --profile release
      - run: mv target/aarch64-unknown-linux-musl/release/teamspeak-autochannel target/aarch64-unknown-linux-musl/release/teamspeak-autochannel_linux_aarch64
      - uses: actions/upload-artifact@v2
        with:
          name: teamspeak-autochannel_linux_aarch64
          path: target/aarch64-unknown-linux-musl/release/teamspeak-autochannel_linux_aarch64
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/aarch64-unknown-linux-musl/release/teamspeak-autochannel_linux_aarch64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
